### ISSUE TITLE
HTML <select> widget not shown

### ISSUE THREAD

**Issue by marhoy** [Igalia/meta-webkit#139]
I'm using meta-webkit in [balena-wpe](https://github.com/marhoy/balena-wpe) that runs on a rpi3. X is not started, and cog is used to start the browser.

The <select> widget is not rendered, so it is not possible to click and select from a dropdown menu (see attached screenshot). 

Any idea about why this happens and how to fix it?
Is it due to lack of some native widget?

The same webpage works with Chrome/Safari on Mac/iOS.

![IMG_0005](https://user-images.githubusercontent.com/22790786/73199721-a4ab8e00-4135-11ea-9811-5ce81ca7ebe5.jpg)

**Comment by clopez** [comment]
This happens because there is currently no support for platform native widgets on WPE.
On WebKitGTK `<select>` gets rendered with GTK toolkit widgets, but WPE doesn't use GTK.
Upstream bug would be https://bugs.webkit.org/show_bug.cgi?id=193817

A possible workaround would be to use some JavaScript/CSS to render custom selects items
Example: https://codepen.io/wallaceerick/pen/ctsCz
