### ISSUE TITLE
Does wpebackend-fdo actually need virtual/libgl?

### ISSUE THREAD

**Issue by mrstinky** [Igalia/meta-webkit#33]
I had the following build error: `ERROR: Nothing PROVIDES 'virtual/libgl'`

The wpebackend-fdo recipe says: `DEPENDS = "wpebackend glib-2.0 libxkbcommon wayland virtual/libgl"`

Is that correct? Or should it be `virtual/egl`?

**Comment by psaavedra** [comment]
I probably need a second opinion but AFAIK: 

* in practice, no real matters because very probable that you libgl provider and the egl provider set in the machine definition will be the same
* semantically, looks more precise establish the dependency against EGL. I don't see any explicit usage of libgl in the code and, moreover, the cmake rules looks for EGL libraries (`FindEGL.cmake`) in `WPEBackend-fdo`


Anyway I need to do run this change with different setups to be sure.

**Comment by psaavedra** [comment]
Tested (https://gitlab.com/saavedra.pablo/meta-perf-browser/pipelines/36594298)
